id = "ventorjr"
name = "VentoRJR"
version = "0.0.3"
schema_version = 1
authors = ["Deniz Akşimşek <deniz@aksimsek.tr>", "Bob Rockefeller"]
description = "Highlighting for the Vento templating language with YAML front matter support"
repository = "https://github.com/bobrocke/zed-vento"

[grammars.vento]
repository = "https://github.com/bobrocke/tree-sitter-vento/"
commit = "d94fd182e2adb6cacff47a0b4e0773e31e6e3682"
