id = "vento-improved"
name = "Vento Improved"
version = "0.0.3"
schema_version = 1
authors = ["Deniz Akşimşek <deniz@aksimsek.tr>", "Bob Rockefeller"]
description = "Highlighting for the Vento templating language with YAML front matter support"
repository = "https://github.com/bobrocke/zed-vento"

[grammars.vento]
repository = "https://github.com/bobrocke/tree-sitter-better-vento/"
commit = "8cdbffcfbef956e5a45a66ec05e8bf2f373dfb32"
